version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: henrique-dozzle_web_1
      APP_PORT: 8080
  
  web:
    image: amir20/dozzle:v8.11.6@sha256:4ce6ccd57f1146f592c04c4b0f9a1fbb74f7aa4305ab2c6629f2ec9147e08a3d
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock