version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: henrique-dozzle_web_1
      APP_PORT: 8080
  
  web:
    image: amir20/dozzle:v8.11.4@sha256:31293186a51c3abf4f7cefca3265b4c123e1c6e86322098e40cb1e7d329bfb51
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock